### ISSUE TITLE
-1751

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Dynamic-Dark-Mode#18]
I thought this would be an enhancement, but it turns out otherwise it’s a race condition. No wonder how I wasn’t able to reproduce this.

https://forums.developer.apple.com/thread/90892

**Comment by ApolloZhu** [comment]
I assume this has been fixed

**Comment by ApolloZhu** [comment]
After Xcode crashes for 

```
Dynamic Dark Mode(6380,0x700001afe000) malloc: Non-aligned pointer 0x6000021381e0 being freed (2)
Dynamic Dark Mode(6380,0x700001afe000) malloc: *** set a breakpoint in malloc_error_break to debug
```

when reconnecting to Wi-Fi, re-running the app will result in -1751 when executing Apple Script files

**Comment by Moulick** [comment]
I am still having this error :(

**Comment by bjw29** [comment]
Still seeing this issue,  How would we go about resolving this?
